on:
  push:
    branches:
      - master

jobs:
  deploy_job:
    runs-on: self-hosted
    name: Continous Deployment
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.SSH_USER }}
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: '.'
          remote_path: '/var/www/jumpingbot'
          args: '-o ConnectTimeout=5'

      - name: Updating npm
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/wap && npm install
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: restart pm2
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/wap && pm2 restart ecosystem.config.js
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
