on:
  push:
    branches:
      - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Continous Deployment
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Pull from ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/jumpingbot && git pull
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Updating npm
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/jumpingbot && npm install
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: restart pm2
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/jumpingbot && pm2 restart jumpingbot
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

